### ISSUE TITLE
bug: error on loading

### ISSUE THREAD

**Issue by madtomic** [MLGEditz/CreativeLimiter#5]
Fresh install and I get this error.

```java
[14:35:09 INFO]: [CreativeLimiter] Enabling CreativeLimiter v2.7
[14:35:09 WARN]: java.io.IOException: The system cannot find the path specified
[14:35:09 WARN]:        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[14:35:09 WARN]:        at java.io.File.createNewFile(Unknown Source)
[14:35:09 WARN]:        at nl.mlgeditz.creativelimiter.config.FileManager.createFile(FileManager.java:31)
[14:35:09 WARN]:        at nl.mlgeditz.creativelimiter.Main.onEnable(Main.java:58)
[14:35:09 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[14:35:09 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[14:35:09 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[14:35:09 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
[14:35:09 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
[14:35:09 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[14:35:09 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[14:35:09 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[14:35:09 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
[14:35:09 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[14:35:09 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Comment by wouterdedroog** [comment]
Try creating the CreativeLimiter folder youself, and see if that resolves the issue. I'll poke @MLGEditz in the hope he will look into fixing this issue. Thanks for reporting :)

**Comment by madtomic** [comment]
CreativeLimiter folder and all files generated fine. I hope  he will see what is the issue is.

This error seems to go away after restart but I think, this issue should be addressed anyway.

**Comment by MLGEditz** [comment]
Hi thanks for mentioning.

This is a known issue and as you experienced reloading/restarting your server is the only solution right now.

I will fix this problem after my vacation.

Kind Regards,
MLGEditz

**Comment by MLGEditz** [comment]
Hi thanks for mentioning.

This is a known issue and as you experienced reloading/restarting your server is the only solution right now.

I will fix this problem after my vacation.

Kind Regards,
MLGEditz
